FROM mysql:8.4.7

ARG WORKDIR

WORKDIR ${WORKDIR}

# all .sql and .sh files inside /docker-entrypoint-initdb.d will be executed
# https://hub.docker.com/_/mariadb#initializing-the-database-contents
COPY init.sql /docker-entrypoint-initdb.d/init.sql
