//////////////////////////////////////////////////////
// DB per community di ricette per studenti fuorisede
// 15 entità – completo e scalabile
//////////////////////////////////////////////////////

//////////////////////////////////////////////////////
// 1) Utenti
//////////////////////////////////////////////////////
Table Users {
  ID char(36) [primary key]
  Username varchar [not null, unique]
  Email varchar [not null, unique]
  Password char(255) [not null]
  Avatar blob
  Admin bool [default: false, not null]
  Deleted bool [default: false, not null]
}

//////////////////////////////////////////////////////
// 2) Ricette
//////////////////////////////////////////////////////
Table Recipes {
  ID char(36) [primary key]
  Title varchar(50) [not null]
  Description text 
  Difficulty enum('Easy','Medium','Hard')
  CookingTime int
  Servings int
  UserID char(36) [not null]
  CreatedAt timestamp [default: `CURRENT_TIMESTAMP`, not null]
  Deleted bool [default: false, not null]
}

Ref: Recipes.UserID > Users.ID

Table RecipeSteps {
  RecipeID char(36) [not null]
  StepNumber int [not null, increment]
  Instruction text [not null]
  Photo blob
  indexes {
    (RecipeID, StepNumber) [pk]
  }
}

Ref: RecipeSteps.RecipeID > Recipes.ID


//////////////////////////////////////////////////////
// 4) Ingredienti delle ricette (N-N)
//////////////////////////////////////////////////////
Table RecipeIngredients {
  RecipeID char(36) [primary key]
  IngredientID integer [not null,increment]
  "Name" varchar(50) [not null]
  Quantity varchar(50) [not null]
  BarCode varchar(20) 
}

Ref: RecipeIngredients.RecipeID > Recipes.ID

//////////////////////////////////////////////////////
// 5) Commenti
//////////////////////////////////////////////////////
Table Reviews {
  ID integer [primary key, increment]
  UserID char(36) [not null]
  RecipeID integer [not null]
  Body text [not null]
  Rating int [not null, default: 0, note: 'Valutazione da 1 a 5']
  CreatedAt timestamp [default: `CURRENT_TIMESTAMP`, not null]
}

Ref: Reviews.UserID > Users.ID
Ref: Reviews.RecipeID > Recipes.ID

//////////////////////////////////////////////////////
// 6) Foto ricette
//////////////////////////////////////////////////////
Table RecipePhotos {
  ID integer [primary key, increment]
  RecipeID integer [not null]
  Photo blob [not null]
}

Ref: RecipePhotos.RecipeID > Recipes.ID


//////////////////////////////////////////////////////
// 8) Likes ricette
//////////////////////////////////////////////////////
Table RecipeLikes {
  UserID char(36) [not null]
  RecipeID integer [not null]
  indexes {(RecipeID, UserID) [pk]}
}

Ref: RecipeLikes.UserID > Users.ID
Ref: RecipeLikes.RecipeID > Recipes.ID

Table Tags {
  ID char(36) [primary key]
  "Name" varchar(20) [not null, unique]
}

Table RecipeTags {
  RecipeID char(36)
  TagID char(36)
  indexes {
    (RecipeID, TagID) [pk]
  }
}
Ref: RecipeTags.RecipeID > Recipes.ID
Ref: RecipeTags.TagID > Tags.ID
